services:
  db:
    image: mongo:latest
    volumes:
      - ./data/db:/data/db
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    ports:
      - 27017:27017
    networks:
      - app-network
    env_file:
      - .env

  backend:
    build: ./backend
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      - PYTHONPATH=/app
      - MONGO_URI=mongodb://${MONGO_USER}:${MONGO_PASS}@db:${MONGO_PORT}/${MONGO_DB_NAME}
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_started
    env_file:
      - .env
  
  arq_worker:
    build: ./backend
    command: ["arq", "api.service.tasks.WorkerSettings"]
    volumes:
      - ./backend:/app
    working_dir: /app
    networks:
      - app-network
    environment:
      - PYTHONPATH=/app
    depends_on:
      redis:
        condition: service_healthy
      backend:
        condition: service_started
    env_file:
      - .env

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mongo_data:
  node_modules:
  redis_data:

networks:
  app-network:
    driver: bridge
