services:
  db:
    image: mongo:latest
    volumes:
      - ./data/db:/data/db
    environment:
      - MONGO_INITDB_DATABASE=your_db_name
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://root:example@db:27017/your_db_name
    depends_on:
      - db

  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

volumes:
  mongo_data:
