from bson import ObjectId
from . import (
    football_college,
    football_hs
    # mens_c_basketball,
    # mens_hs_basketball,
    # womens_c_basketball,
    # womens_hs_basketball
)


LEVEL_CONSTANTS = {
    ("football", "mens", "high_school"): {
        "_id": ObjectId("67017efbb2d2f30e9c5ecc52"),
        "k_value": 0.7,
        "home_advantage": 3,
        "average_game_score": 50,
        "game_set_len": 7
    },
    ("football", "mens", "college"): {
        "_id": ObjectId("67017efbb2d2f30e9c5ecc53"),
        "k_value": 0.69,
        "home_advantage": 3,
        "average_game_score": 60,
        "game_set_len": 7
    },
    ("basketball", "mens", "high_school"): {
        "_id": ObjectId("67017efbb2d2f30e9c5ecc54"),
        "k_value": 0.43,
        "home_advantage": 4.5,
        "average_game_score": 106,
        "game_set_len": 7
    },
    ("basketball", "mens", "college"): {
        "_id": ObjectId("67017efbb2d2f30e9c5ecc55"),
        "k_value": 0.31,
        "home_advantage": 4.5,
        "average_game_score": 136,
        "game_set_len": 1
    },
    ("basketball", "womens", "high_school"): {
        "_id": ObjectId("67017efbb2d2f30e9c5ecc56"),
        "k_value": 0.43,
        "home_advantage": 4.5,
        "average_game_score": 83,
        "game_set_len": 7
    },
    ("basketball", "womens", "college"): {
        "_id": ObjectId("67017efbb2d2f30e9c5ecc57"),
        "k_value": 0.31,
        "home_advantage": 4.5,
        "average_game_score": 122,
        "game_set_len": 1
    }
}

DIVISION_FOOTBALL = {
    1: '1A',
    2: '2A',
    3: '3A',
    4: '4A',
    5: '5A',
    6: '6A',
    7: '6-MAN',
    8: '8-MAN',
    9: 'NCAA 2',
    10: 'NCAA 1 FCS',
    11: 'NCAA 1 FBS',
    12: 'NAIA',
    13: 'Other',
    14: 'NCAA 3',
    None: None
}

FOOTBALL_COLLEGE_CONF = {
    1: 'RMAC',
    2: 'Big 10',
    3: 'Mid-South',
    4: 'New Jersey',
    5: 'Great Plains',
    6: 'ACC',
    7: 'NAIA Ind',
    8: 'Heart of America',
    9: 'Frontier',
    10: 'Kansas',
    11: 'North Star',
    12: 'Mid-States',
    13: 'Sooner',
    14: 'Great Midwest',
    15: 'Mountain West',
    16: 'Conf USA',
    17: 'SEC',
    18: 'FBS Ind',
    19: 'SWAC',
    20: 'Atlantic Sun',
    21: 'Northeast',
    22: 'Mid Eastern',
    23: 'Big Sky',
    24: 'Southern IAC',
    25: 'Southern',
    26: 'Pioneer',
    27: 'Western Athletic',
    28: 'Other',
    29: 'Big 12',
    30: 'Pac 12',
    31: 'South Atlantic',
    32: 'Central',
    33: 'Great American',
    34: 'Mid America',
    35: 'Mountain East',
    36: 'Penn St',
    37: 'Michigan',
    38: 'Heartland',
    39: 'Northeast-10',
    40: 'USA South',
    41: 'SAA',
    42: 'New England',
    43: 'Commonwealth Coast',
    44: 'MASCAC',
    45: 'Mid Atlantic',
    46: 'East Coast',
    47: 'Centennial',
    48: 'Empire 8',
    49: 'Lone Star',
    50: 'Sunbelt',
    51: 'Northern Sun',
    52: 'Presidents',
    53: 'Mid-American',
    54: 'NCAA 2 Ind',
    55: 'Minnesota',
    56: 'Ill and Wisc',
    57: 'Northern Atlantic',
    58: 'American SW',
    59: 'Old Dominion',
    60: 'Ohio',
    61: 'Midwest',
    62: 'Big South',
    63: 'Patriot',
    64: 'American Rivers',
    65: 'Liberty',
    66: 'Southern Cal',
    67: 'American Athletic',
    68: 'Upper Midwest',
    69: 'Great Lakes',
    70: 'North Coast',
    71: 'Colonial',
    72: 'Gulf South',
    73: 'Ohio Valley',
    74: 'Northwest',
    75: 'Southland',
    76: 'Missouri Valley',
    77: 'Wisconsin',
    78: 'NCAA 3 Ind',
    79: 'Ivy',
    80: 'NESCAC',
    None: None
}

STATES = {
    1: {'state_name': 'Colorado', 'state_code': 'CO'},
    3: {'state_name': 'New Mexico', 'state_code': 'NM'},
    4: {'state_name': 'Nevada', 'state_code': 'NV'},
    5: {'state_name': 'Nebraska', 'state_code': 'NE'},
    6: {'state_name': 'Utah', 'state_code': 'UT'},
    7: {'state_name': 'Alabama', 'state_code': 'AL'},
    8: {'state_name': 'Alaska', 'state_code': 'AK'},
    9: {'state_name': 'Arizona', 'state_code': 'AZ'},
    10: {'state_name': 'Arkansas', 'state_code': 'AR'},
    11: {'state_name': 'California', 'state_code': 'CA'},
    12: {'state_name': 'Connecticut', 'state_code': 'CT'},
    13: {'state_name': 'Delaware', 'state_code': 'DE'},
    14: {'state_name': 'Florida', 'state_code': 'FL'},
    15: {'state_name': 'Georgia', 'state_code': 'GA'},
    16: {'state_name': 'Hawaii', 'state_code': 'HI'},
    17: {'state_name': 'Idaho', 'state_code': 'ID'},
    18: {'state_name': 'Illinois', 'state_code': 'IL'},
    19: {'state_name': 'Indiana', 'state_code': 'IN'},
    20: {'state_name': 'Iowa', 'state_code': 'IA'},
    21: {'state_name': 'Kansas', 'state_code': 'KS'},
    22: {'state_name': 'Kentucky', 'state_code': 'KY'},
    23: {'state_name': 'Louisiana', 'state_code': 'LA'},
    24: {'state_name': 'Maine', 'state_code': 'ME'},
    25: {'state_name': 'Maryland', 'state_code': 'MD'},
    26: {'state_name': 'Massachusetts', 'state_code': 'MA'},
    27: {'state_name': 'Michigan', 'state_code': 'MI'},
    28: {'state_name': 'Minnesota', 'state_code': 'MN'},
    29: {'state_name': 'Mississippi', 'state_code': 'MS'},
    30: {'state_name': 'Missouri', 'state_code': 'MO'},
    31: {'state_name': 'Montana', 'state_code': 'MT'},
    32: {'state_name': 'New Hampshire', 'state_code': 'NH'},
    33: {'state_name': 'New Jersey', 'state_code': 'NJ'},
    34: {'state_name': 'New York', 'state_code': 'NY'},
    35: {'state_name': 'North Carolina', 'state_code': 'NC'},
    36: {'state_name': 'North Dakota', 'state_code': 'ND'},
    37: {'state_name': 'Ohio', 'state_code': 'OH'},
    38: {'state_name': 'Oklahoma', 'state_code': 'OK'},
    39: {'state_name': 'Oregon', 'state_code': 'OR'},
    40: {'state_name': 'Pennsylvania', 'state_code': 'PA'},
    41: {'state_name': 'Rhode Island', 'state_code': 'RI'},
    42: {'state_name': 'South Carolina', 'state_code': 'SC'},
    43: {'state_name': 'South Dakota', 'state_code': 'SD'},
    44: {'state_name': 'Tennessee', 'state_code': 'TN'},
    45: {'state_name': 'Texas', 'state_code': 'TX'},
    46: {'state_name': 'Vermont', 'state_code': 'VT'},
    47: {'state_name': 'Virginia', 'state_code': 'VA'},
    48: {'state_name': 'Washington', 'state_code': 'WA'},
    49: {'state_name': 'West Virginia', 'state_code': 'WV'},
    50: {'state_name': 'Wisconsin', 'state_code': 'WI'},
    51: {'state_name': 'Wyoming', 'state_code': 'WY'},
    52: {'state_name': 'Canada', 'state_code': 'CAN'},
    53: {'state_name': 'District of Columbia', 'state_code': 'DC'},
    54: {'state_name': 'British Columbia', 'state_code': 'BC'},
}

DIVISION_BASKETBALL = {
    1: "1A",
    2: "2A",
    3: "3A",
    4: "4A",
    5: "5A",
    6: "6A",
    7: "6-MAN",
    8: "8-MAN",
    9: "NCAA 1",
    10: "NCAA 2",
    11: "NCAA 3",
    12: "NAIA",
    13: "Other"
}

CONFERENCE_CB = {
    1: 'Big 12',
    2: 'Big 10',
    3: 'Big East',
    4: 'SEC',
    5: 'Pac 12',
    6: 'ACC',
    7: 'Mountain West',
    8: 'American Athletic',
    9: 'West Coast',
    10: 'Conference USA',
    11: 'Atlantic 10',
    12: 'NCAA 1 Independent',
    13: 'Northeast',
    14: 'Western Athletic',
    15: 'Missouri Valley',
    16: 'Sun Belt',
    17: 'Ivy',
    18: 'SWAC',
    19: 'Big West',
    20: 'MAC',
    21: 'Southern',
    22: 'Atlantic Sun',
    23: 'Southland',
    24: 'Big Sky',
    25: 'Colonial',
    26: 'Sunshine State',
    27: 'Old Dominion',
    28: 'Cascade',
    29: 'Metro Atalantic',
    30: 'MEAC',
    31: 'Summit',
    32: 'Big South',
    33: 'Ohio Valley',
    34: 'Patriot',
    35: 'Horizon',
    36: 'America East',
    37: 'Mid-America',
    38: 'Mountain East',
    39: 'Penn St',
    40: 'RMAC',
    41: 'California',
    42: 'Lone Star',
    43: 'Great American',
    44: 'Pacific West',
    45: 'Northern Sun',
    46: 'Coast-to-Coast',
    47: 'Crossroads',
    48: 'South Atlantic',
    49: 'Great Lakes Valley',
    50: 'Peach Belt',
    51: 'Ohio',
    52: 'Northeast-10',
    53: 'Great Midwest',
    54: 'Carolinas',
    55: 'Great Lakes',
    56: 'Gulf South',
    57: 'Central',
    58: 'East Coast',
    59: 'NCAA 2 Independent',
    60: 'Central Atlantic',
    61: 'Southern IAC',
    62: 'Great Northwest',
    63: 'Great Northeast',
    64: 'NCAA 3 Independent',
    65: 'Illinois-Wisconsin',
    66: 'Centennial',
    67: 'SUNY',
    68: 'Wisconsin',
    69: 'Little East',
    70: 'Univeristy',
    71: 'American SW',
    72: 'NESCAC',
    73: 'Michigan',
    74: 'Minnesota',
    75: 'Southern Collegiate',
    76: 'New England',
    77: 'Commonwealth Coast',
    78: 'North Coast Atlantic',
    79: 'Southern Athletic',
    80: 'American Rivers',
    81: 'Midwest',
    82: 'Golden State',
    83: 'Wolverine-Hoosier',
    84: 'Southern Cal',
    85: 'Mid-South',
    86: 'Landmark',
    87: 'Heart of America',
    88: 'Northern Atlantic',
    89: 'Great Plains',
    90: 'Northwest',
    91: 'Gulf Coast',
    92: 'New Jersey',
    93: 'Frontier',
    94: 'USA South',
    95: 'Upper Midwest',
    96: 'Conference of the South',
    97: 'Empire 8',
    98: 'Kansas',
    99: 'Sooner',
    101: 'Middle Atlantic',
    102: 'Liberty League',
    103: 'Southern States',
    104: 'Allegheny Mountain',
    105: 'United East',
    106: 'Atlantic East',
    107: 'Skyline',
    108: 'Red River',
    109: 'New England Collegiate',
    110: 'California Pacific',
    111: 'Presidents',
    112: 'The Sun',
    113: 'City Univ of NY',
    114: 'Continental',
    115: 'St Louis',
    116: 'Chicagoland',
    117: 'Colonial States',
    118: 'River States',
    119: 'North Atlantic',
    120: 'Massachusetts',
    121: 'Heartland',
    122: 'NAIA Independent',
    123: 'Appalachian',
    124: 'American MW',
    125: 'North Star',
    126: 'Other',
}

CONSTANTS_MAP = {
    ("football", "mens", "high_school"): (
        football_hs.FOOTBALL_TEAMS_HS,
        football_hs.FOOTBALL_TEAMS_IDS_HS,
        DIVISION_FOOTBALL
    ),
    ("football", "mens", "college"): (
        football_college.FOOTBALL_TEAMS_COLLEGE,
        football_college.FOOTBALL_TEAMS_IDS_COLLEGE,
        DIVISION_FOOTBALL,
        FOOTBALL_COLLEGE_CONF
    ),
    ("basketball", "mens", "high_school"): (
        # mens_hs_basketball.MHS_BB_TEAM_INFO,
        # mens_hs_basketball.MHS_BB_IDS,
        DIVISION_BASKETBALL
    ),
    ("basketball", "mens", "college"): (
        # mens_c_basketball.MC_BB_TEAM_INFO,
        # mens_c_basketball.MC_BB_IDS,
        DIVISION_BASKETBALL,
        CONFERENCE_CB
    ),
    ("basketball", "womens", "high_school"): (
        # womens_hs_basketball.HS_WBB_TEAM_INFO,
        # womens_hs_basketball.HS_WBB_IDS,
        DIVISION_BASKETBALL
    ),
    ("basketball", "womens", "college"): (
        # womens_c_basketball.C_WBB_TEAM_INFO,
        # womens_c_basketball.C_WBB_IDS,
        DIVISION_BASKETBALL,
        CONFERENCE_CB
    )
}
