name: CI/CD Pipeline

# Run this workflow on any push to the main branch
on:
  push:
    branches: [ "main" ]

jobs:
  # Define a job for building, testing, and deploying
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker (if you're using Docker)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build and test FastAPI and React (you can add more steps here)
      - name: Build and Test
        run: |
          docker-compose up --build -d
          # Run backend tests
          docker-compose exec fastapi pytest
          # Run frontend tests
          docker-compose exec react npm test
