name: CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Build and run Docker Compose
      - name: Build and Test
        env:
          MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
          MONGO_USER: ${{ secrets.MONGO_USER }}
          MONGO_PASS: ${{ secrets.MONGO_PASS }}
          MONGO_PORT: ${{ secrets.MONGO_PORT }}
        run: |
          docker-compose up --build -d
          # Run tests or other commands here
